;;; Automatically generated by ‘recentf’ on Sun Dec  3 21:45:16 2023.

(setq recentf-list
      '(
        "~/emms/emms-history"
        "~/.emacs.d/data/treemacs/persist.org"
        "~/.emacs.d/init.el"
        "~/GAME/main.cpp"
        "~/GAME/CMakeLists.txt"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
